from practicies.practica1 import *
from practicies.practica2 import *
from practicies.practica3 import *
from practicies.practica41 import *
from practicies.practica42 import *
from practicies.practica43 import *
from practicies.practica5 import *
from practicies.practica71 import *
from practicies.practica72 import *
from practicies.practica73 import *
from practicies.practica74 import *
from practicies.practica8 import *
